### ISSUE TITLE
Viable successor to `gatsby-plugin-advanced-sitemap`?

### ISSUE THREAD

**Issue by tony** [Chefclub/gatsby-plugin-complex-sitemaps#4]
https://github.com/TryGhost/gatsby-plugin-advanced-sitemap ([gatsby plugin page](https://www.gatsbyjs.com/plugins/gatsby-plugin-advanced-sitemap/?=sitemap)) has been out of date for 4.0 for months.

Is this a viable alternative for those facing issues?  I bet the users on see https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/issues/199 would love a before / after of how to change their config to move over

**Comment by AdrianGuery** [comment]
Yes it's a real viable alternative, we created it precisely because _**gatsby-plugin-advanced-sitemap**_ no longer met our needs.
Thanks for the indication, we will create this week a section in the readme to show the differences between these plugins, and how to migrate.

**Comment by tony** [comment]
@AdrianGuery This is going to be a chart topper, there is a backfunnel of users in that thread.  Definitely do what you can for documentation and polish it up

**Comment by AdrianGuery** [comment]
@tony 
We just opened a issue : https://github.com/Chefclub/gatsby-plugin-complex-sitemaps/issues/5
We will do that today

**Comment by AdrianGuery** [comment]
Hi,
There is the new documentation : 
https://github.com/Chefclub/gatsby-plugin-complex-sitemaps/blob/master/docs/advanced-sitemap-migration.md

**Comment by tony** [comment]
@AdrianGuery Thank you!

I posted in the thread here: https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/issues/199#issuecomment-1049843925

Hopefully this makes its way to the top of gatsby plugins

For now I will close this, if there's no objections
