### ISSUE TITLE
Docs on filterPages option

### ISSUE THREAD

**Issue by ansmlc** [Chefclub/gatsby-plugin-complex-sitemaps#7]
Could you give a little more detail on how the filterPages option works, and include an example in the existing config sample? 

> Function that take the raw queryName results data and should true to keep this node or false to remove this node

Edit: Figured it out, didn't quite get it at first as the wording is a little weird.

**Comment by AdrianGuery** [comment]
Hi @ansmlc,
Feel free to do a PR to improve the wording, we will accept it with pleasure.
